### ISSUE TITLE
Definition of incremental_export

### ISSUE THREAD

**Issue by tjchambers** [zendesk/zendesk_api_client_rb#251]
I am trying to use the incremental_export facility to fetch users that have been created since a start time. I have in two cases so far (no logs unfortunately) received the same user TWICE in the same collection. 

I am unclear about the definition of incremental_export and what it is testing. Is it testing updated_at? Is it testing against created_at? If they are BOTH AFTER my start time should I receive the same user TWICE?

Would appreciate a clearer statement of what to expect.

**Comment by steved** [comment]
Hm, that does seem very odd. The expectation is that you would only get one instance per payload since the data is keyed on (what is essentially) the updated_at. 

Just to clarify. By collection, do you mean one request? Or one set of requests spanning many start_time parameters?

If you do get specific logging, do you mind sending an email to api@zendesk.com?

**Comment by tjchambers** [comment]
I am talking about a single request returning a single collection.

Scenario is …

- I do incremental poll and get nothing (correct).
- I save the current time as my start time
- A user is added
- A user then verifies
- minutes later I poll again using my saved start time
- I get a collection that when iterated has the same user id = same user twice.

I am using the Ruby api to get the data, so it is conceivable it is in the collection handling in the API code.

I just know I got the same id twice (my logging not yours - the numbers are the users zendesk ID):

20150721143903/ruby13.log-[Tue 21 Jul 19:55:48.800] (252244-capture_zendesk)
20150721143903/ruby13.log:1173721519 denis@denismulder.com denis@denismulder.com
20150721143903/ruby13.log-Sent AaPackageComms style email to BusDev Support {bd@schellingpoint.com}
20150721143903/ruby13.log:1173721519 denis@denismulder.com denis@denismulder.com
20150721143903/ruby13.log-Sent AaPackageComms style email to BusDev Support {bd@schellingpoint.com}
20150721143903/ruby13.log-[Tue 21 Jul 19:55:50.541] ----- done!
20150721143903/ruby13.log-

Code snippet:

collection = ZendeskAPI::User.incremental_export(@client, start)
done = []
collection.all do |user|
  if selected?(done, start, user)
    puts user.id.to_s + ' ' + user.name + ' ' + user.email
    deliver(user)
    done << user.id
  end
end

My new code as you can see has an array to capture the provided ID’s so I can skip them in same request. I don’t think that SHOULD be necessary, but it is based upon my experience.

**Comment by steved** [comment]
Definitely doesn't seem to be correct. Thanks for the reproduction steps, I'll see what I can find out.

**Comment by tjchambers** [comment]
Appreciate it.

BTW those times are UTC and the ID is in Zendesk (duh), so if you want to look at any logs on your end you can. The request used API token and my tchambers@schellinpoint.com <mailto:tchambers@schellinpoint.com> email address.

**Comment by steved** [comment]
Was able to reproduce. The problem is actually that two separate requests (since Collection#all will page automatically) can have an overlap. Here's the scenario:

If two users are included in the initial export -- User A with `updated_at` = 123 and User B with `updated_at` = 124 -- a request to `start_time` = 123 will include both (and return with an `end_time` of 124). The next_page parameter of that request, however, will be one with a start_time = 124. Since the collection pages automatically until the end_time parameter matches the request, that next request will include User B again and then complete.

Since time-based APIs are tricky, we err on the side of caution and include more data rather than missing some. Unfortunately, a call to Collection#all will make this look like the user is returned twice for the same request. Your solution of an array of seen ids is probably best, especially if you only want newly created users.
