### ISSUE TITLE
Finding number of tickets created since a particular timestamp...

### ISSUE THREAD

**Issue by trekr5** [zendesk/zendesk_api_client_rb#260]
Hello,

When I make a direct API call to find the number of tickets created since a particular timestamp(1439799280), I use:-

    curl -u [email]:token:[token] https://[url]/api/v2/incremental/tickets.json?start_time=1439799280
and I can see as part of the response returned, a count of the number of new tickets created.

When I use the zendesk_api ruby client, I use

    tick = client.tickets.incremental_export(1439799280)

However I can't count the number of tickets returned in this collection. Doing a tick.count returns a -1. How would i find the number of new tickets in this collection?

Investigating further, I can see that the result(tick) returned is a ZendeskAPI::Collection object. How do I interrogate this object. I've tried looking at the Collection class and running methods like count and fetch against it and I get an error of "couldn't authenticate you"

**Comment by steved** [comment]
`tick.count` should work, you're receiving a `-1` because the authentication is failing. Make sure the client you configured can properly fetch a user (`client.current_user`)

Collections are lazy-loaded arrays. Most array methods will trigger an API call (like `count` or `map`). There are some custom methods that will raise exceptions (`fetch!`, `all!`) on errors.
