### ISSUE TITLE
On resize appends width to the iframe

### ISSUE THREAD

**Issue by lightofdavinci** [zendesk/zendesk_api_client_rb#403]
As an example, this also happens on zendesk url here - https://support.zendesk.com/hc/en-us/?_ga=2.114159559.150078641.1572906022-1522072559.1555625264. 
<img width="453" alt="Screen Shot 2019-11-04 at 2 50 32 PM" src="https://user-images.githubusercontent.com/16696703/68164726-79d4e380-ff12-11e9-962e-3ad85a8d63e2.png">
Any resizing of the window will cause adding of the same inline styles width.

**Comment by nogates** [comment]
@lightofdavinci I am close this issue since this is related with the web widget and this repository is for the official ruby API client. However, I've forwarded this to the team that handles the web widget and they are investigating the issue, so thanks for reporting it! If you want to know more about it, I suggest you create a ticket on zendesk support.
